In [1]:
print("hello world")

hello world


In [2]:
 print(10)

10


In [3]:
x=10.6
type(x)

float

In [4]:
a=[1,2,3,4]
type(a)

list

In [5]:
a=(1,2,3)
type(a)

tuple

In [6]:
a={1,2,3}
type(a)

set

In [7]:
 import numpy as np

In [8]:
x=[[1,2,3],[4,5,6],[7,8,9]]
np.array(x)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [10]:
np.arange(1,30,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
np.zeros((3,6),int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [15]:
np.ones(3,int)

array([1, 1, 1])

In [16]:
 np.linspace(0,1,5)
    #equal division from 0 to 1 to 5 parts

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
np.eye((10))
#matrix of size 10X10 where the diagnols are 1 eye refers to identity matrix

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [18]:
np.random.rand(3,5)
#random numbers in a matrix of size 3X5 where all numbers between 0 to 1

array([[0.71764749, 0.23850268, 0.20107542, 0.90616678, 0.22832471],
       [0.85088902, 0.48007569, 0.43124472, 0.73626356, 0.08188482],
       [0.94829097, 0.22110426, 0.41590037, 0.5894402 , 0.92147026]])

In [19]:
np.random.randn(4,5)
#randn also allows negative numbers from -1 to 1

array([[ 0.92467279, -1.11266921, -0.68943542, -1.69520477,  1.0527109 ],
       [-1.66372816,  1.03154159, -0.62464605, -0.64840228,  0.41839356],
       [-0.20853591, -0.94680157, -0.15583538,  1.21753415,  0.40500465],
       [-0.54527671,  0.3347384 , -1.89978846, -0.37744025, -0.15798679]])

In [20]:
np.random.randint(4,10)
#generates A RANDOM INTEGER BETWEEN 4 AND 10 last number will not be generated 

9

In [21]:
np.random.randint(20,56,100)
#from 20 to 56 generated 100 numbers

array([52, 29, 51, 31, 44, 32, 45, 28, 51, 20, 51, 42, 45, 22, 41, 27, 51,
       44, 51, 42, 33, 32, 47, 50, 41, 39, 44, 45, 45, 24, 54, 26, 29, 53,
       22, 32, 27, 22, 51, 34, 35, 31, 41, 41, 53, 37, 32, 46, 31, 20, 27,
       52, 37, 49, 22, 42, 40, 52, 48, 39, 20, 43, 29, 37, 54, 54, 39, 32,
       38, 53, 30, 28, 25, 52, 36, 53, 22, 38, 53, 25, 42, 33, 29, 28, 41,
       27, 29, 41, 21, 44, 45, 29, 33, 36, 33, 45, 39, 33, 53, 50])

In [22]:
x=np.random.randint(20,50,50)
x

array([41, 20, 29, 22, 46, 39, 23, 40, 44, 30, 30, 21, 20, 31, 31, 45, 24,
       24, 22, 48, 23, 36, 22, 27, 35, 30, 44, 43, 29, 25, 24, 22, 45, 37,
       33, 27, 45, 45, 43, 36, 27, 27, 39, 30, 36, 48, 49, 34, 29, 46])

In [23]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [24]:
np.random.randint(0,100,20)

array([98, 60, 42, 98, 27, 15, 62, 65, 66, 54, 78, 69, 10, 80, 27, 13, 67,
       74, 76, 72])

In [25]:
x=np.arange(30)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [26]:
x.reshape(5,6)
#rearranging the single dimensional array to 2d array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [27]:
y=np.random.randint(0,100,20)
y

array([91, 98, 77, 23, 40, 57, 50, 30, 73, 92, 79, 39, 71, 97, 72, 91, 52,
       40, 62, 90])

In [28]:
y.max()
#maximum in previously generated array

98

In [29]:
y.argmax()
#1st occured index of max element

1

In [30]:
y.min()

23

In [31]:
y.argmin()

3

In [32]:
z=np.eye(5)
z

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
z.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
a=np.random.rand(3,4)
a

array([[0.92320248, 0.40308928, 0.35846609, 0.96383839],
       [0.36402519, 0.31994313, 0.41365761, 0.22377918],
       [0.49235614, 0.30441909, 0.12473352, 0.58581696]])

In [35]:
a.T
#to find transverese of a matrix

array([[0.92320248, 0.36402519, 0.49235614],
       [0.40308928, 0.31994313, 0.30441909],
       [0.35846609, 0.41365761, 0.12473352],
       [0.96383839, 0.22377918, 0.58581696]])

In [36]:
x=np.arange(10,21)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [37]:
x[5]

15

In [38]:
x[2:5]
#index 2,3,4

array([12, 13, 14])

In [39]:
x[1:4]=100
x
#changing all three elements at a time

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [40]:
y=x[0:8]
y

array([ 10, 100, 100, 100,  14,  15,  16,  17])

In [41]:
y[:]=200
y

array([200, 200, 200, 200, 200, 200, 200, 200])

In [42]:
#2d array

In [43]:
a=np.array(([1,2,3,4],[5,6,7,8],[9,0,10,11]))
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9,  0, 10, 11]])

In [44]:
a[1,2]
#2nd row 3rd column

7

In [45]:
a[1,:]

array([5, 6, 7, 8])

In [46]:
a[1]

array([5, 6, 7, 8])

In [47]:
a[:,(3,2)]
#all rows first we selected the 4th row and the 3rd row

array([[ 4,  3],
       [ 8,  7],
       [11, 10]])

In [48]:
x=np.arange(1,20)

In [49]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [50]:
x+x

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [51]:
2*x

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [52]:
np.exp(x)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [53]:
x-x

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [54]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [55]:
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [56]:
np.max(x)

19

In [57]:
np.min(x)

1

In [58]:
np.argmax(x)

18

In [59]:
np.argmin(x)

0

In [60]:
np.square(x)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [61]:
np.std(x)
#standard deviation of all elements in the array
#all the operations are done on the main created array

5.477225575051661

In [62]:
np.var(x)
#variance

30.0

In [63]:
np.mean(x)

10.0

In [64]:
a=np.random.randn(3,4)
a

array([[-0.07087958,  0.06440592,  0.22063132, -1.25607831],
       [-1.05689325,  1.14160464, -0.31594166, -0.35475908],
       [-0.91099705, -0.01875857, -0.1625245 ,  0.34319506]])

In [65]:
np.round(a,decimals=2)
#round off above created array

array([[-0.07,  0.06,  0.22, -1.26],
       [-1.06,  1.14, -0.32, -0.35],
       [-0.91, -0.02, -0.16,  0.34]])

In [66]:
x=np.array(['a','b','c','d'])
np.unique(x)

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [67]:
#pandas library

In [68]:
import pandas as pd
import numpy as np

In [69]:
x=['a','b','c','d'] #labels
y=[1,2,3,4] #list
z=np.array([10,20,30,40]) #array
p={'a':10,'b':20,'c':30,'d':40} #dictionary

In [70]:
pd.Series(data=y)
#created a data dictionary with a single column with the data in y array we donot assign any index but automatically taken

0    1
1    2
2    3
3    4
dtype: int64

In [71]:
pd.Series(data=y,index=x)
#above we have not specified index here we specified

a    1
b    2
c    3
d    4
dtype: int64

In [72]:
pd.Series(z,y)
#no need to write data and index all times

1    10
2    20
3    30
4    40
dtype: int32

In [73]:
pd.Series(p)

a    10
b    20
c    30
d    40
dtype: int64

In [74]:
#pandas dataframing and indexing

In [75]:
x=pd.Series([1,2,3,4],index=['gaya3','sweety','sravya','chinnu'])
x

gaya3     1
sweety    2
sravya    3
chinnu    4
dtype: int64

In [76]:
x['gaya3']

1

In [77]:
y=pd.Series([5,6,7,8],index=['gaya3','sweety','sravya','chinnu'])
#this is a type of dataframe
y

gaya3     5
sweety    6
sravya    7
chinnu    8
dtype: int64

In [78]:
x+y
#here same column must be there otherwise Nan will come as output

gaya3      6
sweety     8
sravya    10
chinnu    12
dtype: int64

In [79]:
y=pd.Series([5,6,7,8],index=['gaya3','sweety','srav','chinnu'])
y

gaya3     5
sweety    6
srav      7
chinnu    8
dtype: int64

In [80]:
x+y
#here when we add sravya and srav both are different so nan

chinnu    12.0
gaya3      6.0
srav       NaN
sravya     NaN
sweety     8.0
dtype: float64

In [81]:
#when we want to create more number of colunms ten we will use the dataframes
#now for creating a dataframe with n no of rows and m no of columns with random nos DataFrame syntax index refers to the rows
#columns refers to the names of the columns if we pass all the names in the form of the string then use split function
dataframe1=pd.DataFrame(np.random.rand(5,4),index='A B C D E'.split(),columns='sweety gaya3 sravya chinnu'.split())
dataframe1
#random nos from 0 to 1 with 5 rows and 4 cols

sweety     gaya3    sravya    chinnu
A  0.595216  0.481832  0.557343  0.953405
B  0.082746  0.101301  0.403711  0.566275
C  0.912520  0.767082  0.904774  0.999343
D  0.798666  0.983033  0.115764  0.653521
E  0.443206  0.002449  0.661549  0.843603

In [82]:
#fetching only onecolumn
dataframe1['gaya3']

A    0.481832
B    0.101301
C    0.767082
D    0.983033
E    0.002449
Name: gaya3, dtype: float64

In [83]:
#fetching more than one cols
dataframe1[['gaya3','sweety']]

gaya3    sweety
A  0.481832  0.595216
B  0.101301  0.082746
C  0.767082  0.912520
D  0.983033  0.798666
E  0.002449  0.443206

In [84]:
#creating a new col and adding to dataframe
dataframe1['amma']=dataframe1['gaya3']+dataframe1['sravya']
dataframe1

sweety     gaya3    sravya    chinnu      amma
A  0.595216  0.481832  0.557343  0.953405  1.039176
B  0.082746  0.101301  0.403711  0.566275  0.505012
C  0.912520  0.767082  0.904774  0.999343  1.671856
D  0.798666  0.983033  0.115764  0.653521  1.098797
E  0.443206  0.002449  0.661549  0.843603  0.663997

In [85]:
#another way of creating a dataframe with more number of cols is creating a dictionary and then convert it into dataframe
df={"a":['1','2','3','4'],"b":[1,2,3,4],"c":['m','n','o','p']}
#a dictionary is created with 3 cols a,b,c where each col contains alist of items so placed in square braces
df1=pd.DataFrame(df)
#converting dictionary to dataframe
df1

a  b  c
0  1  1  m
1  2  2  n
2  3  3  o
3  4  4  p

In [86]:
#removing a particular column
df1.drop("a",axis=1)
#here 1 refers to index position of col
#no need to write df1 for printing if we write it we will get original table not removed table

b  c
0  1  m
1  2  n
2  3  o
3  4  p

In [87]:
#to remove a row
df1.drop(2)
#2 index row will be deleted

a  b  c
0  1  1  m
1  2  2  n
3  4  4  p

In [88]:
#importing dataset using pandas
#working with data sets

In [89]:
import numpy as np
import pandas as pd

In [90]:
df=pd.read_csv("CardioGoodFitness-1.csv")

In [91]:
df.shape
#to find number of rows and columns

(180, 9)

In [92]:
df

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  \
0     TM195   18    Male         14        Single      3        4   29562   
1     TM195   19    Male         15        Single      2        3   31836   
2     TM195   19  Female         14     Partnered      4        3   30699   
3     TM195   19    Male         12        Single      3        3   32973   
4     TM195   20    Male         13     Partnered      4        2   35247   
..      ...  ...     ...        ...           ...    ...      ...     ...   
175   TM798   40    Male         21        Single      6        5   83416   
176   TM798   42    Male         18        Single      5        4   89641   
177   TM798   45    Male         16        Single      5        5   90886   
178   TM798   47    Male         18     Partnered      4        5  104581   
179   TM798   48    Male         18     Partnered      4        5   95508   

     Miles  
0      112  
1       75  
2       66  
3       85  
4       47  
..     ...  
175    200  
176    200  
177    160  
178    120  
179    180  

[180 rows x 9 columns]

In [93]:
df.head()
#if noting is mentiooned inside the parantheses top five rows will be displayed
#i we give no as parameter those many rows will be displayed

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  Miles
0   TM195   18    Male         14        Single      3        4   29562    112
1   TM195   19    Male         15        Single      2        3   31836     75
2   TM195   19  Female         14     Partnered      4        3   30699     66
3   TM195   19    Male         12        Single      3        3   32973     85
4   TM195   20    Male         13     Partnered      4        2   35247     47

In [94]:
df.head(15)

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  \
0    TM195   18    Male         14        Single      3        4   29562   
1    TM195   19    Male         15        Single      2        3   31836   
2    TM195   19  Female         14     Partnered      4        3   30699   
3    TM195   19    Male         12        Single      3        3   32973   
4    TM195   20    Male         13     Partnered      4        2   35247   
5    TM195   20  Female         14     Partnered      3        3   32973   
6    TM195   21  Female         14     Partnered      3        3   35247   
7    TM195   21    Male         13        Single      3        3   32973   
8    TM195   21    Male         15        Single      5        4   35247   
9    TM195   21  Female         15     Partnered      2        3   37521   
10   TM195   22    Male         14        Single      3        3   36384   
11   TM195   22  Female         14     Partnered      3        2   35247   
12   TM195   22  Female         16        Single      4        3   36384   
13   TM195   22  Female         14        Single      3        3   35247   
14   TM195   23    Male         16     Partnered      3        1   38658   

    Miles  
0     112  
1      75  
2      66  
3      85  
4      47  
5      66  
6      75  
7      85  
8     141  
9      85  
10     85  
11     66  
12     75  
13     75  
14     47

In [95]:
df.tail()
#last five
#similar to head

Product  Age Gender  Education MaritalStatus  Usage  Fitness  Income  \
175   TM798   40   Male         21        Single      6        5   83416   
176   TM798   42   Male         18        Single      5        4   89641   
177   TM798   45   Male         16        Single      5        5   90886   
178   TM798   47   Male         18     Partnered      4        5  104581   
179   TM798   48   Male         18     Partnered      4        5   95508   

     Miles  
175    200  
176    200  
177    160  
178    120  
179    180

In [96]:
df.tail(12)

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  \
168   TM798   30    Male         18     Partnered      5        4  103336   
169   TM798   30    Male         18     Partnered      5        5   99601   
170   TM798   31    Male         16     Partnered      6        5   89641   
171   TM798   33  Female         18     Partnered      4        5   95866   
172   TM798   34    Male         16        Single      5        5   92131   
173   TM798   35    Male         16     Partnered      4        5   92131   
174   TM798   38    Male         18     Partnered      5        5  104581   
175   TM798   40    Male         21        Single      6        5   83416   
176   TM798   42    Male         18        Single      5        4   89641   
177   TM798   45    Male         16        Single      5        5   90886   
178   TM798   47    Male         18     Partnered      4        5  104581   
179   TM798   48    Male         18     Partnered      4        5   95508   

     Miles  
168    160  
169    150  
170    260  
171    200  
172    150  
173    360  
174    150  
175    200  
176    200  
177    160  
178    120  
179    180

In [97]:
df.sample()
#by default any one of the random row will be displayed

Product  Age Gender  Education MaritalStatus  Usage  Fitness  Income  Miles
85   TM498   21   Male         16     Partnered      2        2   34110     42

In [98]:
df.sample(15)
#15 random rows displayed

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  \
6     TM195   21  Female         14     Partnered      3        3   35247   
76    TM195   44  Female         16        Single      3        4   57987   
150   TM798   25    Male         16     Partnered      4        5   49801   
60    TM195   33  Female         16     Partnered      3        3   46617   
79    TM195   50  Female         16     Partnered      3        3   64809   
36    TM195   26    Male         16     Partnered      2        2   53439   
83    TM498   20    Male         14        Single      3        3   38658   
161   TM798   27    Male         21     Partnered      4        4   90886   
118   TM498   32    Male         16        Single      4        3   60261   
115   TM498   31    Male         16     Partnered      3        3   52302   
122   TM498   33    Male         16     Partnered      3        3   51165   
130   TM498   35  Female         16        Single      3        2   50028   
46    TM195   28    Male         14        Single      3        3   52302   
85    TM498   21    Male         16     Partnered      2        2   34110   
154   TM798   25    Male         18     Partnered      6        4   70966   

     Miles  
6       75  
76      75  
150    120  
60      85  
79      66  
36      47  
83      95  
161    100  
118    127  
115     95  
122     95  
130     64  
46     103  
85      42  
154    180

In [99]:
df.dtypes
#datatype of each and every column
#object refers to string datatype

Product          object
Age               int64
Gender           object
Education         int64
MaritalStatus    object
Usage             int64
Fitness           int64
Income            int64
Miles             int64
dtype: object

In [100]:
df.info()
#how many observations are there in the dataset along with the datatype
#non null refers to how many columns are completely filled

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Product        180 non-null    object
 1   Age            180 non-null    int64 
 2   Gender         180 non-null    object
 3   Education      180 non-null    int64 
 4   MaritalStatus  180 non-null    object
 5   Usage          180 non-null    int64 
 6   Fitness        180 non-null    int64 
 7   Income         180 non-null    int64 
 8   Miles          180 non-null    int64 
dtypes: int64(6), object(3)
memory usage: 12.8+ KB


In [101]:
df.isnull().sum()
#sum of number of missing values in each column

Product          0
Age              0
Gender           0
Education        0
MaritalStatus    0
Usage            0
Fitness          0
Income           0
Miles            0
dtype: int64

In [102]:
df.describe()
#entire statistic data will be obtained

Age   Education       Usage     Fitness         Income  \
count  180.000000  180.000000  180.000000  180.000000     180.000000   
mean    28.788889   15.572222    3.455556    3.311111   53719.577778   
std      6.943498    1.617055    1.084797    0.958869   16506.684226   
min     18.000000   12.000000    2.000000    1.000000   29562.000000   
25%     24.000000   14.000000    3.000000    3.000000   44058.750000   
50%     26.000000   16.000000    3.000000    3.000000   50596.500000   
75%     33.000000   16.000000    4.000000    4.000000   58668.000000   
max     50.000000   21.000000    7.000000    5.000000  104581.000000   

            Miles  
count  180.000000  
mean   103.194444  
std     51.863605  
min     21.000000  
25%     66.000000  
50%     94.000000  
75%    114.750000  
max    360.000000

In [103]:
df.describe(include="all")

Product         Age Gender   Education MaritalStatus       Usage  \
count      180  180.000000    180  180.000000           180  180.000000   
unique       3         NaN      2         NaN             2         NaN   
top      TM195         NaN   Male         NaN     Partnered         NaN   
freq        80         NaN    104         NaN           107         NaN   
mean       NaN   28.788889    NaN   15.572222           NaN    3.455556   
std        NaN    6.943498    NaN    1.617055           NaN    1.084797   
min        NaN   18.000000    NaN   12.000000           NaN    2.000000   
25%        NaN   24.000000    NaN   14.000000           NaN    3.000000   
50%        NaN   26.000000    NaN   16.000000           NaN    3.000000   
75%        NaN   33.000000    NaN   16.000000           NaN    4.000000   
max        NaN   50.000000    NaN   21.000000           NaN    7.000000   

           Fitness         Income       Miles  
count   180.000000     180.000000  180.000000  
unique         NaN            NaN         NaN  
top            NaN            NaN         NaN  
freq           NaN            NaN         NaN  
mean      3.311111   53719.577778  103.194444  
std       0.958869   16506.684226   51.863605  
min       1.000000   29562.000000   21.000000  
25%       3.000000   44058.750000   66.000000  
50%       3.000000   50596.500000   94.000000  
75%       4.000000   58668.000000  114.750000  
max       5.000000  104581.000000  360.000000